# .tmuxinator.yml

# Usage
# 1. Open a terminal and navigate to where the .tmuxinator.yml file is located
# 2. Run the command: tmuxinator start .
# 3. This will start a new tmux session with the specified windows and panes

name: gelc
root: ../

# This runs EXACTLY ONCE in the background before windows/panes are opened
on_project_start:
  - git switch main
  - git pull

windows:
  - workspace:
      layout: even-vertical # Splits panes horizontally (one on top, one on bottom)
      panes:
        - pane_1:
            - tmux set -g mouse on
            - conda env list
            - git switch -c feature/ec2_job_1
            - git push -u origin feature/ec2_job_1
        - pane_2:
            - clear
