# Conda environment clean up and set up procedure
# Download 'condaenv.yml'
# Open an Anaconda Prompt terminal
# cd Downloads
# conda env list
# conda remove --name my_env --all
# conda env create --file=condaenv.yml
# conda activate my_env
# pip install gogettr truthbrush webvtt-py pymupdf
# conda list
# conda deactivate
# exit
# Regarding Google Cloud Python APIs, please check https://github.com/googleapis/google-cloud-python
name: my_env
dependencies:
  - beautifulsoup4
  - bibtexparser
  - boto3
  - dash
  - demoji
  - folium
  - gensim
#  - gogettr
  - google-cloud-storage
  - google-cloud-translate
  - google-cloud-videointelligence
  - google-cloud-vision
  - ipython
  - jupyterlab
  - jupyterlab-variableinspector
  - jupytext
  - lxml
  - matplotlib
  - nltk
  - numpy
  - openai
  - openpyxl
  - pandas
  - pandas-stubs
  - pandoc
  - plotly
  - pyinstaller
#  - pymupdf
  - pypdf
  - pySmartDL
  - pyspark
  - python-docx
  - python-dotenv
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - selenium
  - spacy
  - spacy-model-en_core_web_sm
  - spyder
  - tqdm
#  - truthbrush
  - validators
#  - webvtt-py
  - wordcloud
  - yake
  - yt-dlp
