# Conda environment clean up and set up procedure
# Download 'condaenv.yaml'
# Open an Anaconda Prompt terminal
# cd Downloads
# conda env list
# conda remove --name my_env --all
# conda env create --file=condaenv.yaml
# conda activate my_env
# conda list
# conda deactivate
# exit
# Regarding Google Cloud Python APIs, please check https://github.com/googleapis/google-cloud-python
name: my_env
dependencies:
  - beautifulsoup4
  - bibtexparser
#  - boto3
#  - dash
#  - demoji
#  - folium
#  - gensim
#  - google-cloud-storage
#  - google-cloud-translate
#  - google-cloud-videointelligence
#  - google-cloud-vision
  - ipython
  - jupyterlab
#  - jupyterlab-variableinspector
#  - jupytext
  - lxml
  - matplotlib
  - nltk
  - numpy
  - openai
  - openpyxl
  - pandas
  - pandas-stubs
#  - pandoc
  - plotly
#  - pyinstaller
#  - pypdf
#  - pyside6
#  - pySmartDL
#  - pyspark
  - python-docx
  - python-dotenv
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - selenium
#  - spacy
#  - spyder
  - tqdm
  - validators
#  - wordcloud
#  - yake
  - yt-dlp
  - pip
  - pip:
#      - gogettr
      - pymupdf
#      - truthbrush
#      - webvtt-py
